"""Runtime helpers for the Google Maps agent package."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from pydantic_ai import Agent, RunContext
from pydantic_ai.models import KnownModelName, Model
from pydantic_ai.output import PromptedOutput
from pydantic_ai_skills import SkillsToolset

from agents_party.config import settings
from agents_party.domain import ThreadMessage
from agents_party.infrastructure.google_maps import (
    GoogleMapsClientProtocol,
    HttpxGoogleMapsClient,
)
from agents_party.agents.skills import load_builtin_skills

from .models import (
    GoogleMapsAction,
    GoogleMapsInvocation,
    GoogleMapsPlaceSummary,
    GoogleMapsResult,
    GoogleMapsRouteSummary,
)

DEFAULT_GOOGLE_MAPS_MODEL = "google-vertex:gemini-3-flash-preview"

GOOGLE_MAPS_SCOPE_SECTION = """
You answer Slack requests that need Google Maps location lookup, nearby search, address lookup, route lookup, or travel-time estimation.
Use Google Maps tools for factual place and route data instead of guessing from general knowledge.
Return concise Japanese Slack-ready answers.
"""

GOOGLE_MAPS_TOOL_SECTION = """
Choose the tool that best matches the request:
- Use `search_places` for place names, addresses, facility details, or direct location lookup.
- Use `search_nearby` for nearby queries such as `Shinjuku Station near coffee shops`.
- Use `compute_route` for route, distance, travel time, or directions between two locations.
- Default `travel_mode` to `driving` when the user does not specify one.
- Default nearby radius to `1500` meters when the user does not specify one.
"""

GOOGLE_MAPS_LODGING_SECTION = """
When the user is asking where to stay, what area to book, or which hotel area best fits a trip,
load and apply the `lodging-search-advisor` skill before finalizing the answer.
Use that skill to structure the recommendation around area choice, transit burden, late arrival risk,
and value tradeoffs, then use Google Maps tools to verify place candidates, station access, and route practicality.
Do not answer lodging requests from hotel marketing copy alone.
"""

GOOGLE_MAPS_CLARIFIER_SECTION = """
Ask one short blocking question only when route lookup is missing either the origin or the destination.
Do not ask a blocking question when place search or nearby search can proceed from the current request.
"""

GOOGLE_MAPS_OUTPUT_SECTION = """
Return `answered` when you can provide a useful maps response.
Populate `places` with up to five place candidates when a place or nearby search is relevant.
Populate `route` when a route lookup is relevant.
Use `caveats` for limitations, ambiguity, or missing confidence.
Return `clarification_needed` only when a short route question is required.
"""


def _format_thread_transcript(thread_messages: list[ThreadMessage]) -> str:
    """Render Slack thread messages into a stable transcript block.

    Args:
        thread_messages: Normalized Slack thread messages in chronological order.

    Returns:
        Plain-text transcript used as Google Maps context.
    """
    lines: list[str] = []
    for message in thread_messages:
        speaker = message.role.value
        if message.user_id:
            speaker = f"{speaker}:{message.user_id}"
        lines.append(f"[{message.ts}] {speaker} {message.text}")
    return "\n".join(lines)


def build_google_maps_instructions() -> tuple[str, ...]:
    """Return the instruction blocks used by the Google Maps agent.

    Returns:
        Ordered instruction strings fed into the Google Maps agent.
    """
    return (
        "You are a Google Maps specialist for Slack users.",
        GOOGLE_MAPS_SCOPE_SECTION.strip(),
        GOOGLE_MAPS_TOOL_SECTION.strip(),
        GOOGLE_MAPS_LODGING_SECTION.strip(),
        GOOGLE_MAPS_CLARIFIER_SECTION.strip(),
        GOOGLE_MAPS_OUTPUT_SECTION.strip(),
    )


def build_google_maps_prompt(invocation: GoogleMapsInvocation) -> str:
    """Render the Google Maps prompt from a validated Slack invocation.

    Args:
        invocation: Validated Google Maps invocation to encode into the prompt.

    Returns:
        Prompt text containing the current request and optional transcript context.
    """
    sections = [f"Slack request:\n{invocation.text}"]
    transcript = _format_thread_transcript(invocation.thread_messages)
    if transcript:
        sections.append(f"Slack thread transcript:\n{transcript}")
    sections.append("Return the structured Google Maps result for this request.")
    return "\n\n".join(sections)


def _normalize_google_maps_result(output: GoogleMapsResult) -> GoogleMapsResult:
    """Normalize Google Maps output before returning it to callers.

    Args:
        output: Raw Google Maps result generated by the model.

    Returns:
        Normalized Google Maps result.
    """
    if output.action == GoogleMapsAction.CLARIFICATION_NEEDED:
        output.answer = ""
        output.places = []
        output.route = None
        output.caveats = []
        if not output.follow_up_question:
            output.follow_up_question = "出発地と目的地を教えてください。"
        return output

    output.follow_up_question = None
    output.answer = output.answer.strip() or "Google Maps で確認した結果です。"

    normalized_places: list[GoogleMapsPlaceSummary] = []
    seen_place_keys: set[str] = set()
    for place in output.places[:5]:
        key = (
            place.place_id
            or place.google_maps_uri
            or f"{place.name}:{place.formatted_address}"
        ).casefold()
        if key in seen_place_keys:
            continue
        seen_place_keys.add(key)
        normalized_places.append(place)
    output.places = normalized_places[:5]
    output.caveats = [caveat.strip() for caveat in output.caveats if caveat.strip()]
    if output.route is not None:
        output.route.travel_mode = output.route.travel_mode.strip().lower() or "driving"
    return output


def render_google_maps_response(result: GoogleMapsResult) -> str:
    """Render a Slack-ready response from a structured Google Maps result.

    Args:
        result: Structured Google Maps result produced by the runtime.

    Returns:
        Slack-ready response text.
    """
    if result.follow_up_question:
        return result.follow_up_question

    sections = [result.answer.strip()]
    if result.route is not None:
        route_lines = [
            f"- 出発地: {result.route.origin}",
            f"- 目的地: {result.route.destination}",
            f"- 移動手段: {_travel_mode_label(result.route.travel_mode)}",
        ]
        if result.route.summary:
            route_lines.append(f"- 概要: {result.route.summary}")
        if result.route.distance_meters is not None:
            route_lines.append(
                f"- 距離: {_format_distance(result.route.distance_meters)}"
            )
        if result.route.duration_seconds is not None:
            route_lines.append(
                f"- 所要時間: {_format_duration(result.route.duration_seconds)}"
            )
        if result.route.google_maps_uri:
            route_lines.append(f"- Google Maps: {result.route.google_maps_uri}")
        sections.append("ルート:\n" + "\n".join(route_lines))

    if result.places:
        place_lines = []
        for place in result.places:
            details = [place.name]
            if place.formatted_address:
                details.append(place.formatted_address)
            if place.primary_type:
                details.append(f"種別: {place.primary_type}")
            if place.rating is not None:
                rating_text = f"評価: {place.rating:.1f}"
                if place.user_rating_count is not None:
                    rating_text = f"{rating_text} ({place.user_rating_count}件)"
                details.append(rating_text)
            if place.google_maps_uri:
                details.append(f"Google Maps: {place.google_maps_uri}")
            place_lines.append("- " + " | ".join(details))
        sections.append("候補スポット:\n" + "\n".join(place_lines))

    if result.caveats:
        caveat_lines = "\n".join(f"- {caveat}" for caveat in result.caveats)
        sections.append(f"注意点:\n{caveat_lines}")
    return "\n\n".join(section for section in sections if section.strip())


def build_google_maps_agent(
    model: Model | KnownModelName | str | None = None,
    *,
    client: GoogleMapsClientProtocol | None = None,
) -> Agent[None, GoogleMapsResult]:
    """Build the Google Maps agent.

    Args:
        model: Optional provider-qualified Gemini model override for the agent.
        client: Optional injected Google Maps client used by function tools.

    Returns:
        Configured Google Maps agent instance.

    Raises:
        ValueError: If no model or Google Maps API key can be resolved.
    """
    resolved_model = model or settings.google_maps_model or DEFAULT_GOOGLE_MAPS_MODEL
    resolved_client = client or _build_google_maps_client()

    agent = cast(
        Agent[None, GoogleMapsResult],
        Agent(
            resolved_model,
            name="google_maps",
            deps_type=type(None),
            output_type=PromptedOutput(GoogleMapsResult),
            instructions=build_google_maps_instructions(),
            toolsets=[_build_google_maps_skill_toolset()],
            defer_model_check=True,
        ),
    )

    async def search_places(query: str) -> list[GoogleMapsPlaceSummary]:
        """Search Google Maps for places or addresses matching a free-text query.

        Args:
            query: Place name, address, or facility query.

        Returns:
            Up to five matching place summaries.
        """
        return await resolved_client.search_places(query=query)

    async def search_nearby(
        anchor_query: str,
        search_query: str,
        radius_meters: int = 1500,
    ) -> list[GoogleMapsPlaceSummary]:
        """Search Google Maps for places near an anchor location.

        Args:
            anchor_query: Anchor place or address that defines the search center.
            search_query: Nearby place query, such as `coffee shop`.
            radius_meters: Radius around the anchor in meters.

        Returns:
            Up to five nearby place summaries.
        """
        return await resolved_client.search_nearby(
            anchor_query=anchor_query,
            search_query=search_query,
            radius_meters=radius_meters,
        )

    async def compute_route(
        origin: str,
        destination: str,
        travel_mode: str = "driving",
    ) -> GoogleMapsRouteSummary:
        """Compute a Google Maps route between two locations.

        Args:
            origin: Route origin provided by the user.
            destination: Route destination provided by the user.
            travel_mode: Travel mode such as `driving` or `walking`.

        Returns:
            Normalized route summary.
        """
        return await resolved_client.compute_route(
            origin=origin,
            destination=destination,
            travel_mode=travel_mode,
        )

    agent.tool_plain(search_places)
    agent.tool_plain(search_nearby)
    agent.tool_plain(compute_route)

    @agent.output_validator
    def _validate_output(
        _ctx: RunContext[None],
        output: GoogleMapsResult,
    ) -> GoogleMapsResult:
        """Normalize Google Maps output before returning it to callers.

        Args:
            _ctx: Pydantic AI run context, unused during normalization.
            output: Raw Google Maps result generated by the model.

        Returns:
            Normalized Google Maps result.
        """
        return _normalize_google_maps_result(output)

    return agent


async def run_google_maps(
    invocation: Mapping[str, Any] | GoogleMapsInvocation,
    *,
    model: Model | KnownModelName | str | None = None,
    client: GoogleMapsClientProtocol | None = None,
) -> GoogleMapsResult:
    """Run the Google Maps agent for a Slack-originated request.

    Args:
        invocation: Raw or validated Google Maps invocation payload.
        model: Optional provider-qualified model override for this run.
        client: Optional injected Google Maps client for tests or reuse.

    Returns:
        Structured Google Maps result.
    """
    parsed_invocation = (
        invocation
        if isinstance(invocation, GoogleMapsInvocation)
        else GoogleMapsInvocation.from_mapping(invocation)
    )
    managed_client = client or _build_google_maps_client()
    try:
        agent = build_google_maps_agent(model=model, client=managed_client)
        result = await agent.run(build_google_maps_prompt(parsed_invocation))
        return result.output
    finally:
        if client is None:
            await managed_client.aclose()


def _build_google_maps_client() -> HttpxGoogleMapsClient:
    """Create the default Google Maps client from application settings.

    Returns:
        Configured Google Maps HTTP client.

    Raises:
        ValueError: If the Google Maps API key is not configured.
    """
    api_key = settings.google_maps_api_key
    if api_key is None:
        raise ValueError(
            "Google Maps API key is not configured. Set GOOGLE_MAPS_API_KEY before using the Google Maps agent."
        )
    return HttpxGoogleMapsClient(
        api_key=api_key.get_secret_value(),
        language_code=settings.google_maps_language_code,
        region_code=settings.google_maps_region_code,
    )


def _build_google_maps_skill_toolset() -> SkillsToolset:
    """Build the skill toolset exposed to the Google Maps agent.

    Returns:
        Skills toolset limited to lodging-search-advisor.
    """
    lodging_skill = load_builtin_skills()["lodging-search-advisor"]
    return SkillsToolset(skills=[lodging_skill])


def _format_distance(distance_meters: int) -> str:
    """Format a distance in meters for Slack output.

    Args:
        distance_meters: Route distance in meters.

    Returns:
        Human-readable distance string.
    """
    if distance_meters >= 1000:
        return f"{distance_meters / 1000:.1f} km"
    return f"{distance_meters} m"


def _format_duration(duration_seconds: int) -> str:
    """Format a duration in seconds for Slack output.

    Args:
        duration_seconds: Route duration in seconds.

    Returns:
        Human-readable duration string.
    """
    hours, remainder = divmod(duration_seconds, 3600)
    minutes = remainder // 60
    if hours and minutes:
        return f"{hours}時間{minutes}分"
    if hours:
        return f"{hours}時間"
    if minutes:
        return f"{minutes}分"
    return "1分未満"


def _travel_mode_label(travel_mode: str) -> str:
    """Return a Japanese label for a canonical travel mode.

    Args:
        travel_mode: Canonical lower-case travel-mode string.

    Returns:
        Human-readable Japanese label.
    """
    return {
        "driving": "車",
        "walking": "徒歩",
        "bicycling": "自転車",
        "transit": "公共交通機関",
        "two_wheeler": "二輪",
    }.get(travel_mode, travel_mode)


__all__ = [
    "DEFAULT_GOOGLE_MAPS_MODEL",
    "build_google_maps_agent",
    "build_google_maps_instructions",
    "build_google_maps_prompt",
    "render_google_maps_response",
    "run_google_maps",
]
