"""Runtime helpers for the web-research agent package."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from pydantic_ai import (
    Agent,
    CodeExecutionTool,
    RunContext,
    WebFetchTool,
    WebSearchTool,
)
from pydantic_ai.models import KnownModelName, Model
from pydantic_ai.output import PromptedOutput

from agents_party.config import settings
from agents_party.domain import ThreadMessage

from .models import (
    WebResearchAction,
    WebResearchInvocation,
    WebResearchResult,
    WebResearchSource,
)

DEFAULT_WEB_RESEARCH_MODEL = "google-vertex:gemini-3-flash-preview"

WEB_RESEARCH_SCOPE_SECTION = """
You answer Slack requests that require web research, current public information, or source-backed verification.
Prefer primary sources, make time sensitivity explicit, and separate verified facts from inference.
Use exact dates, versions, and release windows whenever the request involves current or changing information.
"""

WEB_RESEARCH_SOURCE_SECTION = """
Search from primary sources outward.
Start with official documentation, vendor pages, standards bodies, government datasets, or original papers when available.
Use secondary sources only to confirm, compare, or fill gaps left by primary sources.
"""

WEB_RESEARCH_CLARIFIER_SECTION = """
Ask one short blocking question only when the request is underspecified in a way that would materially change the research target.
If the user asks for `latest`, `current`, `today`, or similar terms, verify them with web tools before answering.
"""

WEB_RESEARCH_OUTPUT_SECTION = """
Return `answered` when you can provide a useful response.
Keep `answer` concise and Slack-ready, but include enough detail to be decision-ready.
Populate `sources` with the key sources you relied on, each with a title and URL.
Use `caveats` for unresolved uncertainty, scope limits, or facts you could not verify.
Return `clarification_needed` only when a short blocking question is necessary.
"""


def _format_thread_transcript(thread_messages: list[ThreadMessage]) -> str:
    """Render Slack thread messages into a stable transcript block.

    Args:
        thread_messages: Normalized Slack thread messages in chronological order.

    Returns:
        Plain-text transcript used as web-research context.
    """
    lines: list[str] = []
    for message in thread_messages:
        speaker = message.role.value
        if message.user_id:
            speaker = f"{speaker}:{message.user_id}"
        lines.append(f"[{message.ts}] {speaker} {message.text}")
    return "\n".join(lines)


def build_web_research_instructions() -> tuple[str, ...]:
    """Return the instruction blocks used by the web-research agent.

    Returns:
        Ordered instruction strings fed into the web-research agent.
    """
    return (
        "You are a web research specialist for Slack users.",
        WEB_RESEARCH_SCOPE_SECTION.strip(),
        WEB_RESEARCH_SOURCE_SECTION.strip(),
        WEB_RESEARCH_CLARIFIER_SECTION.strip(),
        WEB_RESEARCH_OUTPUT_SECTION.strip(),
    )


def build_web_research_prompt(invocation: WebResearchInvocation) -> str:
    """Render the web-research prompt from a validated Slack invocation.

    Args:
        invocation: Validated web-research invocation to encode into the prompt.

    Returns:
        Prompt text containing the current request and optional transcript context.
    """
    sections = [f"Slack request:\n{invocation.text}"]
    transcript = _format_thread_transcript(invocation.thread_messages)
    if transcript:
        sections.append(f"Slack thread transcript:\n{transcript}")
    sections.append("Return the structured web-research result for this request.")
    return "\n\n".join(sections)


def _normalize_web_research_result(
    output: WebResearchResult,
) -> WebResearchResult:
    """Normalize web-research output before returning it to callers.

    Args:
        output: Raw web-research result generated by the model.

    Returns:
        Normalized web-research result.
    """
    if output.action == WebResearchAction.CLARIFICATION_NEEDED:
        output.answer = ""
        output.sources = []
        output.caveats = []
        if not output.follow_up_question:
            output.follow_up_question = "What exactly should I verify on the web?"
        return output

    output.follow_up_question = None
    output.answer = output.answer.strip() or "I could not produce a research summary."

    normalized_sources: list[WebResearchSource] = []
    seen_urls: set[str] = set()
    for source in output.sources:
        title = source.title.strip()
        url = source.url.strip()
        publisher = source.publisher.strip() if source.publisher else None
        note = source.note.strip() if source.note else None
        if not title or not url:
            continue
        url_key = url.casefold()
        if url_key in seen_urls:
            continue
        seen_urls.add(url_key)
        normalized_sources.append(
            WebResearchSource(
                title=title,
                url=url,
                publisher=publisher or None,
                note=note or None,
            )
        )
    output.sources = normalized_sources
    output.caveats = [caveat.strip() for caveat in output.caveats if caveat.strip()]
    return output


def render_web_research_response(result: WebResearchResult) -> str:
    """Render a Slack-ready response from a structured web-research result.

    Args:
        result: Structured web-research result produced by the runtime.

    Returns:
        Slack-ready response text.
    """
    if result.follow_up_question:
        return result.follow_up_question

    sections = [result.answer.strip()]
    if result.sources:
        source_lines = []
        for source in result.sources:
            prefix = source.title
            if source.publisher:
                prefix = f"{prefix} ({source.publisher})"
            line = f"- {prefix}: {source.url}"
            if source.note:
                line = f"{line} [{source.note}]"
            source_lines.append(line)
        sections.append("Sources:\n" + "\n".join(source_lines))
    if result.caveats:
        caveat_lines = "\n".join(f"- {caveat}" for caveat in result.caveats)
        sections.append(f"Caveats:\n{caveat_lines}")
    return "\n\n".join(section for section in sections if section.strip())


def build_web_research_agent(
    model: Model | KnownModelName | str | None = None,
) -> Agent[None, WebResearchResult]:
    """Build the web-research agent.

    Args:
        model: Optional provider-qualified Gemini model override for the agent.

    Returns:
        Configured web-research agent instance.

    Raises:
        ValueError: If no model can be resolved for the web-research agent.
    """
    resolved_model = model or settings.web_research_model or DEFAULT_WEB_RESEARCH_MODEL
    if resolved_model is None:
        raise ValueError(
            "Web research model is not configured. Set WEB_RESEARCH_MODEL or pass a model explicitly."
        )

    agent = cast(
        Agent[None, WebResearchResult],
        Agent(
            resolved_model,
            name="web_research",
            deps_type=type(None),
            output_type=PromptedOutput(WebResearchResult),
            instructions=build_web_research_instructions(),
            builtin_tools=[
                WebSearchTool(),
                WebFetchTool(),
                CodeExecutionTool(),
            ],
            defer_model_check=True,
        ),
    )

    @agent.output_validator
    def _validate_output(
        _ctx: RunContext[None],
        output: WebResearchResult,
    ) -> WebResearchResult:
        """Normalize web-research output before returning it to callers.

        Args:
            _ctx: Pydantic AI run context, unused during normalization.
            output: Raw web-research result generated by the model.

        Returns:
            Normalized web-research result.
        """
        return _normalize_web_research_result(output)

    return agent


async def run_web_research(
    invocation: Mapping[str, Any] | WebResearchInvocation,
    *,
    model: Model | KnownModelName | str | None = None,
) -> WebResearchResult:
    """Run the web-research agent for a Slack-originated request.

    Args:
        invocation: Raw or validated web-research invocation payload.
        model: Optional provider-qualified model override for this run.

    Returns:
        Structured web-research result.
    """
    parsed_invocation = (
        invocation
        if isinstance(invocation, WebResearchInvocation)
        else WebResearchInvocation.from_mapping(invocation)
    )
    agent = build_web_research_agent(model=model)
    result = await agent.run(build_web_research_prompt(parsed_invocation))
    return result.output


__all__ = [
    "DEFAULT_WEB_RESEARCH_MODEL",
    "build_web_research_agent",
    "build_web_research_instructions",
    "build_web_research_prompt",
    "render_web_research_response",
    "run_web_research",
]
