import type { PostgresMigration } from "./migrations.js";

export const postgresMigrations: readonly PostgresMigration[] = [
  {
    id: "20260330_0001",
    name: "initial_postgres_schema",
    upSql: `
      create table if not exists agents (
        agent_id text primary key,
        enabled boolean not null,
        updated_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_agents_enabled on agents (enabled);

      create table if not exists workspace_app_settings (
        team_id text primary key,
        default_agent_id text,
        thread_auto_reply boolean,
        updated_at timestamp with time zone not null,
        payload json not null
      );

      create table if not exists channel_app_settings (
        team_id text not null,
        channel_id text not null,
        default_agent_id text,
        thread_auto_reply boolean,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, channel_id)
      );

      create table if not exists slack_threads (
        team_id text not null,
        channel_id text not null,
        thread_ts text not null,
        agent_id text,
        root_message_ts text not null,
        last_message_ts text,
        status text not null,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, channel_id, thread_ts)
      );

      create table if not exists slack_installations (
        id integer generated by default as identity primary key,
        client_id text not null,
        app_id text,
        enterprise_id text,
        enterprise_name text,
        enterprise_url text,
        team_id text,
        team_name text,
        bot_token text,
        bot_id text,
        bot_user_id text,
        bot_scopes text,
        bot_refresh_token text,
        bot_token_expires_at timestamp with time zone,
        user_id text not null,
        user_token text,
        user_scopes text,
        user_refresh_token text,
        user_token_expires_at timestamp with time zone,
        incoming_webhook_url text,
        incoming_webhook_channel text,
        incoming_webhook_channel_id text,
        incoming_webhook_configuration_url text,
        is_enterprise_install boolean not null,
        token_type text,
        installed_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_slack_installations_lookup
        on slack_installations (client_id, enterprise_id, team_id, user_id, installed_at);

      create table if not exists slack_bots (
        id integer generated by default as identity primary key,
        client_id text not null,
        app_id text,
        enterprise_id text,
        enterprise_name text,
        team_id text,
        team_name text,
        bot_token text,
        bot_id text,
        bot_user_id text,
        bot_scopes text,
        bot_refresh_token text,
        bot_token_expires_at timestamp with time zone,
        is_enterprise_install boolean not null,
        installed_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_slack_bots_lookup
        on slack_bots (client_id, enterprise_id, team_id, installed_at);

      create table if not exists google_auth_connections (
        team_id text not null,
        slack_user_id text not null,
        google_account_subject text not null,
        google_account_email text,
        connection_status text not null,
        token_expires_at timestamp with time zone,
        refresh_token_expires_at timestamp with time zone,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, slack_user_id, google_account_subject)
      );

      create table if not exists google_oauth_states (
        team_id text not null,
        state_id text not null,
        slack_user_id text not null,
        expires_at timestamp with time zone not null,
        created_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, state_id)
      );

    `,
  },
  {
    id: "20260508_0002",
    name: "salesforce_oauth_schema",
    upSql: `
      create table if not exists salesforce_auth_configs (
        team_id text not null,
        salesforce_org_id text not null,
        salesforce_my_domain_host text not null,
        oauth_client_id text not null,
        status text not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, salesforce_org_id)
      );
      create index if not exists ix_salesforce_auth_configs_status
        on salesforce_auth_configs (team_id, status);

      create table if not exists salesforce_connections (
        team_id text not null,
        slack_user_id text not null,
        salesforce_org_id text not null,
        salesforce_user_id text not null,
        salesforce_username text,
        connection_status text not null,
        token_expires_at timestamp with time zone,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, slack_user_id, salesforce_org_id)
      );
      create index if not exists ix_salesforce_connections_status
        on salesforce_connections (team_id, connection_status);

      create table if not exists salesforce_oauth_states (
        team_id text not null,
        state_id text not null,
        slack_user_id text not null,
        salesforce_org_id text not null,
        expires_at timestamp with time zone not null,
        created_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, state_id)
      );
      create index if not exists ix_salesforce_oauth_states_expires_at
        on salesforce_oauth_states (expires_at);
    `,
  },
  {
    id: "20260508_0003",
    name: "removed_work_item_calendar_links",
    upSql: `
      select 1;
    `,
  },
  {
    id: "20260512_0004",
    name: "agent_model_routing",
    upSql: `
      alter table workspace_app_settings
        add column if not exists default_model_id text;

      alter table channel_app_settings
        add column if not exists default_model_id text;

      alter table slack_threads
        add column if not exists model_id text;

      update workspace_app_settings
      set default_model_id = nullif(btrim(payload ->> 'default_model_id'), '')
      where default_model_id is null
        and nullif(btrim(payload ->> 'default_model_id'), '') is not null;

      update channel_app_settings
      set default_model_id = nullif(btrim(payload ->> 'default_model_id'), '')
      where default_model_id is null
        and nullif(btrim(payload ->> 'default_model_id'), '') is not null;

      update slack_threads
      set model_id = nullif(btrim(payload ->> 'model_id'), '')
      where model_id is null
        and payload ->> 'model_scope' = 'thread'
        and nullif(btrim(payload ->> 'model_id'), '') is not null;
    `,
  },
  {
    id: "20260512_0005",
    name: "workspace_credentials",
    upSql: `
      create table if not exists workspace_credentials (
        team_id text not null,
        provider_kind text not null,
        credential_name text not null,
        secret_encrypted text not null,
        status text not null,
        encryption_scheme text not null,
        key_version text not null,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        created_by_user_id text,
        last_used_at timestamp with time zone,
        last_error_code text,
        payload json not null,
        primary key (team_id, provider_kind, credential_name)
      );
      create index if not exists ix_workspace_credentials_status
        on workspace_credentials (team_id, status);
      create index if not exists ix_workspace_credentials_provider
        on workspace_credentials (team_id, provider_kind);
    `,
  },
  {
    id: "20260512_0006",
    name: "rss_feed_batch_processing",
    upSql: `
      create table if not exists rss_feed_subscriptions (
        id uuid primary key,
        team_id text not null,
        channel_id text not null,
        feed_url text not null,
        enabled boolean not null default true,
        last_seen_published_at timestamp with time zone,
        last_processed_at timestamp with time zone,
        payload jsonb not null default '{}'::jsonb,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        unique (team_id, channel_id, feed_url)
      );
      create index if not exists ix_rss_feed_subscriptions_enabled
        on rss_feed_subscriptions (enabled, team_id, channel_id);
      create index if not exists ix_rss_feed_subscriptions_feed_url
        on rss_feed_subscriptions (feed_url);

      create table if not exists rss_feed_fetch_cache (
        feed_url text primary key,
        etag text,
        last_modified text,
        body text,
        status integer,
        fetched_at timestamp with time zone not null,
        expires_at timestamp with time zone not null,
        error_count integer not null default 0,
        last_error text
      );
      create index if not exists ix_rss_feed_fetch_cache_expires_at
        on rss_feed_fetch_cache (expires_at);

      create table if not exists rss_article_content_cache (
        article_url text primary key,
        content text,
        content_hash text,
        fetched_at timestamp with time zone not null,
        expires_at timestamp with time zone not null,
        fetch_failed_at timestamp with time zone,
        error_count integer not null default 0,
        last_error text
      );
      create index if not exists ix_rss_article_content_cache_expires_at
        on rss_article_content_cache (expires_at);

      create table if not exists rss_processed_articles (
        id uuid primary key,
        subscription_id uuid not null references rss_feed_subscriptions(id),
        article_key text not null,
        article_url text not null,
        published_at timestamp with time zone,
        model_id text,
        model_source text,
        llm_output text,
        slack_channel_id text not null,
        slack_message_ts text,
        processed_at timestamp with time zone not null,
        payload jsonb not null default '{}'::jsonb,
        unique (subscription_id, article_key)
      );
      create index if not exists ix_rss_processed_articles_subscription
        on rss_processed_articles (subscription_id, processed_at desc);
      create index if not exists ix_rss_processed_articles_article_url
        on rss_processed_articles (article_url);
    `,
  },
  {
    id: "20260513_0007",
    name: "salesforce_pdf_workflows",
    upSql: `
      create table if not exists salesforce_pdf_workflow_settings (
        team_id text not null,
        salesforce_org_id text not null,
        action text not null,
        enabled boolean not null,
        template_id text not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, salesforce_org_id, action)
      );
      create index if not exists ix_salesforce_pdf_workflow_settings_enabled
        on salesforce_pdf_workflow_settings (team_id, salesforce_org_id, enabled);

      create table if not exists salesforce_pdf_templates (
        team_id text not null,
        salesforce_org_id text not null,
        template_id text not null,
        action text not null,
        status text not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, salesforce_org_id, template_id)
      );
      create index if not exists ix_salesforce_pdf_templates_action
        on salesforce_pdf_templates (team_id, salesforce_org_id, action, status);
    `,
  },
  {
    id: "20260515_0008",
    name: "app_user_settings",
    upSql: `
      create table if not exists app_user_settings (
        scope_kind text not null,
        scope_id text not null,
        enterprise_id text,
        team_id text,
        slack_user_id text not null,
        locale text,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        updated_by_slack_user_id text,
        payload jsonb not null default '{}'::jsonb,
        primary key (scope_kind, scope_id, slack_user_id),
        constraint ck_app_user_settings_scope_kind
          check (scope_kind in ('enterprise', 'team')),
        constraint ck_app_user_settings_scope
          check (
            (scope_kind = 'enterprise' and enterprise_id is not null and scope_id = enterprise_id)
            or
            (scope_kind = 'team' and enterprise_id is null and team_id is not null and scope_id = team_id)
          ),
        constraint ck_app_user_settings_locale
          check (locale is null or locale in ('ja', 'en'))
      );
      create index if not exists ix_app_user_settings_updated_at
        on app_user_settings (updated_at desc);
    `,
  },
  {
    id: "20260515_0009",
    name: "workspace_enabled_model_ids",
    upSql: `
      alter table workspace_app_settings
        add column if not exists enabled_model_ids jsonb not null default '[]'::jsonb;

      update workspace_app_settings
      set enabled_model_ids = jsonb_build_array(default_model_id)
      where default_model_id is not null
        and btrim(default_model_id) <> ''
        and enabled_model_ids = '[]'::jsonb;
    `,
  },
  {
    id: "20260519_0010",
    name: "workspace_feature_settings",
    upSql: `
      create table if not exists workspace_feature_settings (
        team_id text not null,
        feature_key text not null,
        enabled boolean not null,
        updated_at timestamp with time zone not null,
        updated_by_user_id text,
        payload jsonb not null default '{}'::jsonb,
        primary key (team_id, feature_key)
      );
      create index if not exists ix_workspace_feature_settings_enabled
        on workspace_feature_settings (team_id, enabled);

      create table if not exists channel_feature_settings (
        team_id text not null,
        channel_id text not null,
        feature_key text not null,
        updated_at timestamp with time zone not null,
        updated_by_user_id text,
        payload jsonb not null default '{}'::jsonb,
        primary key (team_id, channel_id, feature_key)
      );
      create index if not exists ix_channel_feature_settings_feature
        on channel_feature_settings (team_id, feature_key);
    `,
  },
  {
    id: "20260525_0011",
    name: "drop_unused_rss_article_content_cache",
    upSql: `
      drop table if exists rss_article_content_cache;
    `,
  },
];
