import type { PostgresMigration } from "./migrations.js";

export const postgresMigrations: readonly PostgresMigration[] = [
  {
    id: "20260330_0001",
    name: "initial_postgres_schema",
    upSql: `
      create table if not exists agents (
        agent_id text primary key,
        enabled boolean not null,
        updated_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_agents_enabled on agents (enabled);

      create table if not exists workspace_app_settings (
        team_id text primary key,
        default_agent_id text,
        thread_auto_reply boolean,
        updated_at timestamp with time zone not null,
        payload json not null
      );

      create table if not exists channel_app_settings (
        team_id text not null,
        channel_id text not null,
        default_agent_id text,
        thread_auto_reply boolean,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, channel_id)
      );

      create table if not exists slack_threads (
        team_id text not null,
        channel_id text not null,
        thread_ts text not null,
        agent_id text,
        root_message_ts text not null,
        last_message_ts text,
        status text not null,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, channel_id, thread_ts)
      );

      create table if not exists slack_installations (
        id integer generated by default as identity primary key,
        client_id text not null,
        app_id text,
        enterprise_id text,
        enterprise_name text,
        enterprise_url text,
        team_id text,
        team_name text,
        bot_token text,
        bot_id text,
        bot_user_id text,
        bot_scopes text,
        bot_refresh_token text,
        bot_token_expires_at timestamp with time zone,
        user_id text not null,
        user_token text,
        user_scopes text,
        user_refresh_token text,
        user_token_expires_at timestamp with time zone,
        incoming_webhook_url text,
        incoming_webhook_channel text,
        incoming_webhook_channel_id text,
        incoming_webhook_configuration_url text,
        is_enterprise_install boolean not null,
        token_type text,
        installed_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_slack_installations_lookup
        on slack_installations (client_id, enterprise_id, team_id, user_id, installed_at);

      create table if not exists slack_bots (
        id integer generated by default as identity primary key,
        client_id text not null,
        app_id text,
        enterprise_id text,
        enterprise_name text,
        team_id text,
        team_name text,
        bot_token text,
        bot_id text,
        bot_user_id text,
        bot_scopes text,
        bot_refresh_token text,
        bot_token_expires_at timestamp with time zone,
        is_enterprise_install boolean not null,
        installed_at timestamp with time zone not null,
        payload json not null
      );
      create index if not exists ix_slack_bots_lookup
        on slack_bots (client_id, enterprise_id, team_id, installed_at);

      create table if not exists google_auth_connections (
        team_id text not null,
        slack_user_id text not null,
        google_account_subject text not null,
        google_account_email text,
        connection_status text not null,
        token_expires_at timestamp with time zone,
        refresh_token_expires_at timestamp with time zone,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, slack_user_id, google_account_subject)
      );

      create table if not exists google_oauth_states (
        team_id text not null,
        state_id text not null,
        slack_user_id text not null,
        expires_at timestamp with time zone not null,
        created_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, state_id)
      );

      create table if not exists work_items (
        team_id text not null,
        work_item_id text not null,
        title text not null,
        status text not null,
        visibility_kind text not null,
        audience_channel_id text,
        primary_assignee_user_id text,
        due_at timestamp with time zone,
        updated_at timestamp with time zone not null,
        completed_at timestamp with time zone,
        payload json not null,
        primary key (team_id, work_item_id)
      );
      create index if not exists ix_work_items_status on work_items (status);
      create index if not exists ix_work_items_visibility_kind on work_items (visibility_kind);
      create index if not exists ix_work_items_channel on work_items (team_id, audience_channel_id);

      create table if not exists work_item_participants (
        team_id text not null,
        work_item_id text not null,
        user_id text not null,
        role text not null,
        attention_profile text not null,
        next_attention_at timestamp with time zone,
        muted_until timestamp with time zone,
        last_seen_event_id text,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, work_item_id, user_id)
      );

      create table if not exists work_item_events (
        team_id text not null,
        work_item_id text not null,
        event_id text not null,
        type text not null,
        occurred_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, work_item_id, event_id)
      );

      create table if not exists work_item_attention_index (
        team_id text not null,
        user_id text not null,
        work_item_id text not null,
        needs_attention_now boolean not null,
        status text not null,
        visibility_kind text not null,
        audience_channel_id text,
        primary_assignee_user_id text,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, user_id, work_item_id)
      );
      create index if not exists ix_work_item_attention_index_needs_attention_now
        on work_item_attention_index (needs_attention_now);
      create index if not exists ix_work_item_attention_index_viewer
        on work_item_attention_index (team_id, user_id, needs_attention_now);
    `,
  },
  {
    id: "20260508_0002",
    name: "salesforce_oauth_schema",
    upSql: `
      create table if not exists salesforce_auth_configs (
        team_id text not null,
        salesforce_org_id text not null,
        salesforce_my_domain_host text not null,
        oauth_client_id text not null,
        status text not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, salesforce_org_id)
      );
      create index if not exists ix_salesforce_auth_configs_status
        on salesforce_auth_configs (team_id, status);

      create table if not exists salesforce_connections (
        team_id text not null,
        slack_user_id text not null,
        salesforce_org_id text not null,
        salesforce_user_id text not null,
        salesforce_username text,
        connection_status text not null,
        token_expires_at timestamp with time zone,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, slack_user_id, salesforce_org_id)
      );
      create index if not exists ix_salesforce_connections_status
        on salesforce_connections (team_id, connection_status);

      create table if not exists salesforce_oauth_states (
        team_id text not null,
        state_id text not null,
        slack_user_id text not null,
        salesforce_org_id text not null,
        expires_at timestamp with time zone not null,
        created_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, state_id)
      );
      create index if not exists ix_salesforce_oauth_states_expires_at
        on salesforce_oauth_states (expires_at);
    `,
  },
  {
    id: "20260508_0003",
    name: "work_item_calendar_links",
    upSql: `
      create table if not exists work_item_calendar_links (
        team_id text not null,
        work_item_id text not null,
        link_id text not null,
        provider_kind text not null,
        external_calendar_id text not null,
        external_event_id text not null,
        event_title_snapshot text,
        starts_at timestamp with time zone,
        ends_at timestamp with time zone,
        is_all_day boolean not null,
        response_status text,
        sync_status text not null,
        last_synced_at timestamp with time zone,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        payload json not null,
        primary key (team_id, work_item_id, link_id),
        constraint uq_work_item_calendar_links_external_event
          unique (team_id, work_item_id, provider_kind, external_calendar_id, external_event_id)
      );
      create index if not exists ix_work_item_calendar_links_external_event
        on work_item_calendar_links
        (team_id, provider_kind, external_calendar_id, external_event_id);
      create index if not exists ix_work_item_calendar_links_sync_status
        on work_item_calendar_links (team_id, sync_status);
    `,
  },
  {
    id: "20260512_0004",
    name: "workspace_credentials",
    upSql: `
      create table if not exists workspace_credentials (
        team_id text not null,
        provider_kind text not null,
        credential_name text not null,
        secret_encrypted text not null,
        status text not null,
        encryption_scheme text not null,
        key_version text not null,
        created_at timestamp with time zone not null,
        updated_at timestamp with time zone not null,
        created_by_user_id text,
        last_used_at timestamp with time zone,
        last_error_code text,
        payload json not null,
        primary key (team_id, provider_kind, credential_name)
      );
      create index if not exists ix_workspace_credentials_status
        on workspace_credentials (team_id, status);
      create index if not exists ix_workspace_credentials_provider
        on workspace_credentials (team_id, provider_kind);
    `,
  },
];
