"""Public API for the work-manager agent package."""

from .messages import (
    _timezone_or_utc,
    build_candidates_question,
    build_created_message,
    build_list_message,
    build_updated_message,
    format_timestamp,
    format_work_item_brief,
)
from .models import (
    WorkManagerAction,
    WorkManagerDeps,
    WorkManagerInvocation,
    WorkManagerPreparedRequest,
    WorkManagerRequestContext,
    WorkManagerRequestPreparer,
    WorkManagerResult,
    WorkManagerTimeContext,
    WorkManagerWorkItem,
)
from .prompts import (
    ATTENTION_REVIEW_BUILDER_SECTION,
    WORK_ITEM_CAPTURE_SECTION,
    WORK_ITEM_CLARIFIER_SECTION,
    build_work_manager_execution_input,
    build_work_manager_executor_instructions,
    build_work_manager_instructions,
    build_work_manager_preparer_instructions,
    build_work_manager_preparer_prompt,
)
from .runtime import (
    build_work_manager_agent,
    build_work_manager_executor_agent,
    build_work_manager_preparer_agent,
    prepare_work_manager_request,
    run_work_manager,
    run_work_manager_preparer,
)

__all__ = [
    "ATTENTION_REVIEW_BUILDER_SECTION",
    "WORK_ITEM_CAPTURE_SECTION",
    "WORK_ITEM_CLARIFIER_SECTION",
    "WorkManagerAction",
    "WorkManagerDeps",
    "WorkManagerInvocation",
    "WorkManagerPreparedRequest",
    "WorkManagerRequestContext",
    "WorkManagerRequestPreparer",
    "WorkManagerResult",
    "WorkManagerTimeContext",
    "WorkManagerWorkItem",
    "_timezone_or_utc",
    "build_candidates_question",
    "build_created_message",
    "build_list_message",
    "build_updated_message",
    "build_work_manager_agent",
    "build_work_manager_execution_input",
    "build_work_manager_executor_agent",
    "build_work_manager_executor_instructions",
    "build_work_manager_instructions",
    "build_work_manager_preparer_agent",
    "build_work_manager_preparer_instructions",
    "build_work_manager_preparer_prompt",
    "format_timestamp",
    "format_work_item_brief",
    "prepare_work_manager_request",
    "run_work_manager",
    "run_work_manager_preparer",
]
