"""Executor-stage helpers for the work-manager agent."""

from __future__ import annotations

from typing import cast

from pydantic_ai import Agent, RunContext
from pydantic_ai.models import KnownModelName, Model

from .models import WorkManagerDeps, WorkManagerResult
from .prompts import build_work_manager_executor_instructions
from agents_party.config import settings


def build_work_manager_executor_agent(
    model: Model | KnownModelName | str | None = None,
) -> Agent[WorkManagerDeps, WorkManagerResult]:
    """Build the work-manager executor agent and register its tools.

    Args:
        model: Optional model override for the work-manager executor.

    Returns:
        Configured work-manager executor agent.

    Raises:
        ValueError: If no work-manager model can be resolved.
    """
    from agents_party.agents.tools import register_work_manager_tools

    resolved_model = model or settings.work_manager_model
    if resolved_model is None:
        raise ValueError(
            "Work manager model is not configured. Set WORK_MANAGER_MODEL or pass a model explicitly."
        )

    agent = cast(
        Agent[WorkManagerDeps, WorkManagerResult],
        Agent(
            resolved_model,
            name="work_manager",
            deps_type=WorkManagerDeps,
            output_type=WorkManagerResult,
            instructions=build_work_manager_executor_instructions(),
            defer_model_check=True,
        ),
    )
    register_work_manager_tools(agent)

    @agent.output_validator
    def _validate_output(
        _ctx: RunContext[WorkManagerDeps],
        output: WorkManagerResult,
    ) -> WorkManagerResult:
        """Normalize work-manager output before returning it to callers.

        Args:
            _ctx: Pydantic AI run context, unused during normalization.
            output: Raw work-manager result generated by the model.

        Returns:
            Normalized work-manager result.
        """
        if output.needs_confirmation and not output.follow_up_question:
            output.follow_up_question = output.message
        if not output.message.strip():
            output.message = "The work manager did not produce a reply."
        return output

    return agent


def build_work_manager_agent(
    model: Model | KnownModelName | str | None = None,
) -> Agent[WorkManagerDeps, WorkManagerResult]:
    """Build the work-manager agent.

    Args:
        model: Optional model override for the work-manager agent.

    Returns:
        Configured work-manager agent.
    """
    return build_work_manager_executor_agent(model=model)


__all__ = [
    "build_work_manager_agent",
    "build_work_manager_executor_agent",
]
